title: Johnny Avakian Portfolio
email: codeavak@gmail.com
description: "Senior Software Engineer portfolio and technical blog."
baseurl: "/portfolio_website"
markdown: kramdown
theme: minima
collections:
  posts:
    output: true
permalink: /blog/:title/
formspree_endpoint: "https://formspree.io/f/your_form_id"
utterances_repo: "codeavak/portfolio_website"
utterances_issue_term: "pathname"
utterances_label: "blog-comment"
